name: 01 | Fetch and Save GCS Prefixes
on:
  push:
    branches:
      - gh-pages  # Trigger on update to the gh-pages branch
  workflow_dispatch:

jobs:
  fetch-gcs-prefixes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes to the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Fetch all nested prefixes using HMAC keys
        env:
          GCS_ACCESS_KEY_ID: ${{ secrets.GCS_ACCESS_KEY_ID }}
          GCS_SECRET_ACCESS_KEY: ${{ secrets.GCS_SECRET_ACCESS_KEY }}
        run: |
          echo "Configuring AWS CLI for GCS"
          
          # Configure AWS CLI for GCS
          aws configure set aws_access_key_id $GCS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $GCS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

          # Recursive function to fetch nested prefixes
          fetch_prefixes() {
            local prefix=$1
            echo "Fetching prefixes for $prefix"

            # Fetch current level
            response=$(aws s3api list-objects-v2 \
              --bucket nmfs_odp_pifsc \
              --prefix "$prefix" \
              --delimiter / \
              --endpoint-url https://storage.googleapis.com)

            # Debug: Save the response for inspection
            echo "$response" | jq . > debug-response.json

            # Parse prefixes (handle null gracefully)
            prefixes=$(echo "$response" | jq -r '.CommonPrefixes[]?.Prefix // empty')

            # Parse files (handle null gracefully)
            files=$(echo "$response" | jq -r '.Contents[]?.Key // empty')

            # Save data
            echo "{\"prefix\": \"$prefix\", \"prefixes\": [$(echo "$prefixes" | jq -R . | jq -s .)], \"files\": [$(echo "$files" | jq -R . | jq -s .)]}" >> nested-prefixes.json

            # Recurse into each prefix
            for sub_prefix in $prefixes; do
              fetch_prefixes "$sub_prefix"
            done
          }

          # Initialize output file
          echo "[" > nested-prefixes.json
          fetch_prefixes "PIFSC/ESD/ARP/pifsc-ai-data-repository/"
          echo "]" >> nested-prefixes.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add nested-prefixes.json debug-response.json
          git commit -m "Updated all nested prefixes and debug response" || echo "No changes to commit"
          git push origin gh-pages
