name: 01 | Fetch and Save GCS Prefixes
on:
  push:
    branches:
      - gh-pages  # Trigger on updates to the gh-pages branch
  workflow_dispatch:

jobs:
  fetch-gcs-prefixes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes to the repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Fetch all nested prefixes using HMAC keys
        env:
          GCS_ACCESS_KEY_ID: ${{ secrets.GCS_ACCESS_KEY_ID }}
          GCS_SECRET_ACCESS_KEY: ${{ secrets.GCS_SECRET_ACCESS_KEY }}
        run: |
          echo "Configuring AWS CLI for GCS"
          
          # Configure AWS CLI for GCS
          aws configure set aws_access_key_id $GCS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $GCS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

          # Temporary file to hold JSON objects
          tmp_file="nested-prefixes-temp.json"
          output_file="nested-prefixes.json"

          # Recursive function to fetch nested prefixes with exclusions
          fetch_prefixes() {
            local prefix=$1
            local depth=$2
            local max_depth=5  # Set your maximum depth limit here

            if [ "$depth" -ge "$max_depth" ]; then
              echo "Reached max depth for $prefix, skipping deeper fetches."
              return
            fi

            # List of excluded folders
            excluded_folders=("raw" "images" "labels" "logs" "database")

            # Check if the current prefix matches any excluded folder
            for excluded in "${excluded_folders[@]}"; do
              if [[ "$prefix" == *"/$excluded/"* ]]; then
                echo "Skipping excluded folder $prefix."
                return
              fi
            done

            echo "Fetching prefixes for $prefix at depth $depth"

            # Fetch current level
            response=$(aws s3api list-objects-v2 \
              --bucket nmfs_odp_pifsc \
              --prefix "$prefix" \
              --delimiter / \
              --endpoint-url https://storage.googleapis.com)

            # Parse prefixes (handle null gracefully)
            prefixes=$(echo "$response" | jq -r '.CommonPrefixes[]?.Prefix // empty')

            # Parse files (handle null gracefully)
            files=$(echo "$response" | jq -r '.Contents[]?.Key // empty')

            # Append the data for the current prefix as a JSON object
            {
              echo "{"
              echo "  \"prefix\": \"$prefix\","
              echo "  \"prefixes\": $(echo "$prefixes" | jq -R . | jq -s .),"
              echo "  \"files\": $(echo "$files" | jq -R . | jq -s .)"
              echo "}"
            } >> "$tmp_file"

            # Recurse into each prefix
            for sub_prefix in $prefixes; do
              fetch_prefixes "$sub_prefix" $((depth + 1))
            done
          }

          # Initialize temporary file
          > "$tmp_file"

          # Fetch prefixes
          fetch_prefixes "PIFSC/ESD/ARP/pifsc-ai-data-repository/" 0  # Start at depth 0

          # Format and finalize JSON array
          jq -s '.' "$tmp_file" > "$output_file"

          # Clean up temporary file
          rm -f "$tmp_file"

          # Validate JSON structure
          if ! jq empty "$output_file"; then
            echo "Error: Invalid JSON structure in $output_file."
            exit 1
          fi

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add nested-prefixes.json
          git commit -m "Updated all nested prefixes with exclusion logic" || echo "No changes to commit"
          git push origin gh-pages
