name: 01 | Fetch and Save GCS Prefixes
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
jobs:
  fetch-gcs-prefixes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Fetch all nested prefixes
        env:
          GCS_ACCESS_KEY_ID: ${{ secrets.GCS_ACCESS_KEY_ID }}
          GCS_SECRET_ACCESS_KEY: ${{ secrets.GCS_SECRET_ACCESS_KEY }}
        run: |
          echo "Configuring AWS CLI for GCS"

          aws configure set aws_access_key_id $GCS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $GCS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

          ROOT_PREFIX="PIFSC/ESD/ARP/pifsc-ai-data-repository/"
          MAX_DEPTH=5
          EXCLUDED_FOLDERS=("raw" "images" "labels" "logs" "database")
          OUTPUT_FILE="nested-prefixes.json"

          echo "[]" > $OUTPUT_FILE

          fetch_prefixes() {
            local prefix=$1
            local depth=$2

            echo "Checking prefix: $prefix at depth $depth"

            if [ "$depth" -ge "$MAX_DEPTH" ]; then
              echo "Max depth reached for prefix: $prefix"
              return
            fi

            # Fetch both CommonPrefixes (folders) and Contents (files)
            response=$(aws s3api list-objects-v2 \
              --bucket nmfs_odp_pifsc \
              --prefix "$prefix" \
              --delimiter / \
              --endpoint-url https://storage.googleapis.com || echo "{}")

            # Fetch prefixes (folders)
            prefixes=$(echo "$response" | jq -r '.CommonPrefixes[]?.Prefix // empty')

            # Fetch files in the current prefix and include .txt files
            files=$(echo "$response" | jq -r '.Contents[]?.Key // empty' | sed "s|^$prefix||" | grep -E '\.txt$')

            # Add prefixes and files to JSON
            json_object=$(jq -n \
              --arg prefix "$prefix" \
              --argjson prefixes "$(echo "$prefixes" | jq -R . | jq -s .)" \
              --argjson files "$(echo "$files" | jq -R . | jq -s .)" \
              '{prefix: $prefix, prefixes: $prefixes, files: $files}')

            jq ". += [$json_object]" $OUTPUT_FILE > tmp.json && mv tmp.json $OUTPUT_FILE

            # Recurse into sub-prefixes
            for sub_prefix in $prefixes; do
              fetch_prefixes "$sub_prefix" $((depth + 1))
            done
          }

          fetch_prefixes "$ROOT_PREFIX" 0

          touch $OUTPUT_FILE

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add nested-prefixes.json
          git commit -m "Updated all nested prefixes with .txt file inclusion" || echo "No changes to commit"
          git push origin gh-pages
